// ?????????????????????????????????????????????????????????????????????????????
// course-data.js  -  Springer Engineering Business Experience Certificate
// Generated by the Course Data Admin Tool on 2026-04-28.
// DO NOT edit this file by hand. Re-generate it from admin.html each semester.
// ?????????????????????????????????????????????????????????????????????????????

var COURSE_DATA = {

  generated: "2026-04-28",

  // ?? 01  Executive Practice & Industry Insight (Gateway Course) ??????????
  gateway: [
    {
      id:      "ENGR 30301",
      name:    "Engineering Executive Forum",
      prof:    "TBD",
      credits: 2,
      sem:     "Fall 2026",
      desc:    "A bi-weekly forum where accomplished engineering alumni — now executives across tech, finance, consulting, and more — share the real story behind their careers. Candid conversations, in-class market simulations, and direct engagement with leaders who have made the jump from engineering to business. You'll leave able to read financial statements, identify executive career pathways, and ask sharper questions about decisions and tradeoffs."
    },
    {
      id:      "ENGR 30301",
      name:    "Engineering Executive Forum",
      prof:    "TBD",
      credits: 2,
      sem:     "Spring 2027",
      desc:    "A bi-weekly forum where accomplished engineering alumni — now executives across tech, finance, consulting, and more — share the real story behind their careers. Candid conversations, in-class market simulations, and direct engagement with leaders who have made the jump from engineering to business. You'll leave able to read financial statements, identify executive career pathways, and ask sharper questions about decisions and tradeoffs."
    }
  ],

  // ?? 02  Business of Engineering Foundational Logic ????????????????????????
  found: [
    {
      id:      "ACCT 20500",
      name:    "Accounting for Engineers",
      prof:    "Kevin Koharki",
      credits: 2,
      sem:     "Fall 2026",
      desc:    "Learn how accounting information drives real decisions — assessing performance, evaluating investments, and comparing firms against rivals. Graded on two projects and participation: no exams. You'll walk away able to analyze financial statements and build Excel models to support business and investment decisions."
    },
    {
      id:      "FIN 20500",
      name:    "Finance for Engineers",
      prof:    "Kevin Koharki",
      credits: 2,
      sem:     "Spring 2027",
      desc:    "The financial fluency every leader needs: reading financial statements, time value of money, discounted cash flow, capital budgeting, and project selection. Heavy use of Excel throughout. You'll walk away able to evaluate investments, interpret financial data, and decide which projects a firm should fund — and why."
    }
  ],

  // ?? 03  Communicating & Leading Self and Teams ????????????????????????????
  comm: [
    {
      id:      "STRT 31200",
      name:    "Venture X1; Discovering Meaningful Problems Worth Solving",
      prof:    "Kosta Grigoriou",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "Pick a problem space you care about and go deep — through stakeholder interviews, market immersion, and customer discovery — until you've identified a validated problem worth building a venture around. The first course in the two-part Venture X sequence."
    },
    {
      id:      "OBHR 44362",
      name:    "Leadership in a Changing World",
      prof:    "TBD",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "Evidence-based course built around practice, feedback, and self-reflection. You'll assess your own leadership strengths, explore what effective leadership looks like in real organizations, and develop a personal leadership philosophy grounded in research."
    },
    {
      id:      "OBHR 33500",
      name:    "Strategic Business Writing",
      prof:    "TBD",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "A targeted communication course. You'll practice executive-level writing, confident oral communication, and the interpersonal leadership behaviors that matter most when working with executives, clients, and cross-functional teams."
    },
    {
      id:      "OBHR 49300",
      name:    "Storytelling with Data",
      prof:    "Doug Pruim",
      credits: 2,
      sem:     "Spring 2027",
      desc:    "Turns data into decisions. You'll learn frameworks for understanding your audience, principles of visual information processing, and hands-on data visualization skills. Final project: a full storytelling-with-data deliverable of your own design."
    },
    {
      id:      "OBHR 44362",
      name:    "Leadership in a Changing World",
      prof:    "TBD",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "Evidence-based course built around practice, feedback, and self-reflection. You'll assess your own leadership strengths, explore what effective leadership looks like in real organizations, and develop a personal leadership philosophy grounded in research."
    },
    {
      id:      "OBHR 33500",
      name:    "Strategic Business Writing",
      prof:    "TBD",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "A targeted communication course. You'll practice executive-level writing, confident oral communication, and the interpersonal leadership behaviors that matter most when working with executives, clients, and cross-functional teams."
    }
  ],

  // ?? 04  Making the Business Case ??????????????????????????????????????????
  biz: [
    {
      id:      "STRT 51010",
      name:    "Student-managed Venture Fund",
      prof:    "Matthew Lynall",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "Act as a venture investment analyst reviewing real startup pitch decks, conducting due diligence, and making actual equity co-investments from a live fund. Includes one-on-one interviews with 8–10 active early-stage investors. Requires an NDA. One of the most distinctive courses on campus."
    },
    {
      id:      "MKTG 32400",
      name:    "Marketing Management",
      prof:    "Stephen Leitch",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "A foundational course covering customer behavior, segmentation, positioning, pricing, promotion, and competitive analysis. You'll develop intuition for analyzing markets and making strategic decisions — and build a foundation for advanced marketing electives."
    },
    {
      id:      "STRT 35500",
      name:    "Consulting Tools & Skills",
      prof:    "John Burr",
      credits: 3,
      sem:     "Fall 2026",
      desc:    "Learn the structured problem-solving process used by top consulting firms — diagnosing root causes, analyzing complex problems, and communicating recommendations clearly. Practical skills for any manager, not just consultants."
    },
    {
      id:      "STRT 220",
      name:    "Making the Business Case",
      prof:    "Dave Randich",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "Analyze real business cases in teams and present recommendations in the format used by top consulting firms and senior executives. Taught by a former President/CEO of four organizations across the US, Europe, and Asia. Ideal for anyone targeting case competitions, consulting, or executive roles."
    },
    {
      id:      "STRT 313",
      name:    "Venture X2; Designing and Building Product to Address Challenge X",
      prof:    "Kostas Grigoriou",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "Starting with a validated problem, you'll design and test your way to a working MVP with a tested business model. Rapid prototyping, real customer feedback loops, customer sales calls, supported by a product-building budget. The second course in the Venture X sequence."
    },
    {
      id:      "MKTG 32400",
      name:    "Marketing Management",
      prof:    "Stephen Leitch",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "A foundational course covering customer behavior, segmentation, positioning, pricing, promotion, and competitive analysis. You'll develop intuition for analyzing markets and making strategic decisions — and build a foundation for advanced marketing electives."
    },
    {
      id:      "STRT 35500",
      name:    "Consulting Tools & Skills",
      prof:    "John Burr",
      credits: 3,
      sem:     "Spring 2027",
      desc:    "Learn the structured problem-solving process used by top consulting firms — diagnosing root causes, analyzing complex problems, and communicating recommendations clearly. Practical skills for any manager, not just consultants."
    }
  ]

};
